import datetime
from snapshot.ca_core import Snapshot, SnapshotReqFile
from snapshot.parser import parse_to_save_file
from epics import PV

class snapshot:
    def __init__(self,filename=None,savepath='/sf/data/applications/snapshot/'):
        self.filename = filename
        self.savepath = savepath
        self.pvnames=[]
        self.pvs=[]
        self.machinepar=[]
        self.message=''
        if self.filename:
            self.openRequestFile(self.filename)


    def openRequestFile(self,filename):
        self.filename = filename
        self.rootname=self.filename.split('/')[-1]
        req_file = SnapshotReqFile(self.filename)
        pvs_list = req_file.read()
        self.pvnames.clear()
        self.machinepar.clear()
        for ele in pvs_list:
            if isinstance(ele,list):
                self.pvnames=ele
            elif isinstance(ele,dict):
                if 'machine_params' in ele.keys():
                    self.machinepar=ele['machine_params']        
        self.connectPVs()
        
    def connectPVs(self):
        self.pvs=[PV(pv) for pv in self.pvnames]
        con = [pv.wait_for_connection(timeout=0.5) for pv in self.pvs]
        for i,val in enumerate(con):
            if val is False:
                print('Cannot connect to PV:', self.pvs[i].pvname)

        
    def getSnapValues(self, force = True):
        values={}
        for pv in self.pvs:
            val = pv.get_with_metadata(timeout=0.1)        
            if force is False and val["value"] is None:
                return False
            values[pv.pvname]={"raw_name":pv.pvname,"val":val["value"]}
            if 'units' in val.keys():
                values[pv.pvname]['egu']=val['units']
            else:
                values[pv.pvname]['egu']=None
            if 'precision' in val.keys():
                values[pv.pvname]['prec']=val['precision']
            else:
                values[pv.pvname]['prec']=None        
        return values
 
    
    def save(self,labels=[],comment="Generated by SFBD-Package",force=True):
        if self.filename is None:
            self.message = 'No Request File Loaded'
            return False

        val = self.getSnapValues(force)
        if isinstance(val,bool) and val == False:
            self.message = 'Unsuccesful reading of PV channels (unforced access)'
            return False
        
        # construct file name
        datetag = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
        root = self.rootname.split('.req')[0]
        files = self.savepath+root+'_'+datetag+'.snap'
        filel = self.savepath+root+'_latest.snap'
        # save file
        parse_to_save_file(val, files, macros=None, symlink_path=filel,
                           comment=comment,labels=[],req_file_name=self.rootname)
        self.message = 'Snapshot saved'
        return True





